version: '3.8'

services:
  app:
    image: gerador-qrcode:latest
    networks:
      - proxy
    volumes:
      - /home/julianoliberato/docker/gerador-qrcode:/var/www/html
      - qr-vendor:/var/www/html/vendor
      - qr-qrcodes:/var/www/html/qrcodes
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.qr.rule=Host(`qr.9level.com.br`)"
        - "traefik.http.routers.qr.entrypoints=websecure"
        - "traefik.http.routers.qr.tls.certresolver=letsencrypt"
        - "traefik.http.routers.qr.middlewares=waf-chain@file"
        - "traefik.http.services.qr.loadbalancer.server.port=80"
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/ || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  qr-vendor:
  qr-qrcodes:

networks:
  proxy:
    external: true
